name: "Yueqi Cao's Homepage"
output:
  html_document:
    theme: jekyll-theme-cayman # specifies the theme
navbar:
  left:
    - text: "Home"
      href: index.html
    - text: "中文版"
      href: index-ch.html
output_dir: "." 
